// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhTpKG85qh9isEMf5z_GUa_FT6mq4G5M8',
    appId: '1:596142903387:web:83bf00f4a1484c10aeaf7e',
    messagingSenderId: '596142903387',
    projectId: 'test-f2b08',
    authDomain: 'test-f2b08.firebaseapp.com',
    storageBucket: 'test-f2b08.appspot.com',
    measurementId: 'G-97BQ0N95N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdUxdKExO0Z9soJiGGvxGGXC-mb_J-9gw',
    appId: '1:596142903387:android:822826c8aa67cd84aeaf7e',
    messagingSenderId: '596142903387',
    projectId: 'test-f2b08',
    storageBucket: 'test-f2b08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1whvJMfjnCxFvfo8WeDOIlZOZw_NqH8',
    appId: '1:596142903387:ios:7418212c82ea407caeaf7e',
    messagingSenderId: '596142903387',
    projectId: 'test-f2b08',
    storageBucket: 'test-f2b08.appspot.com',
    iosClientId: '596142903387-uug147apclgqtmira5c0emsgkusjofb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI1whvJMfjnCxFvfo8WeDOIlZOZw_NqH8',
    appId: '1:596142903387:ios:e9b0364085761303aeaf7e',
    messagingSenderId: '596142903387',
    projectId: 'test-f2b08',
    storageBucket: 'test-f2b08.appspot.com',
    iosClientId: '596142903387-scoge2c10ebn96nn2utpricd4dlg8rlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
